apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarjetas-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: tarjetas
  template:
    metadata:
      labels:
        app: tarjetas
    spec:
      containers:
      - name: tarjetas
        image: gcr.io/terraform-420123/tarjetas:1.0.3
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL         
            value: "postgresql://myuser:password-fastapi@35.226.62.13:5432/tarjetas" 
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: port
