apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - name: usuarios
        image: gcr.io/terraform-420123/usuarios:1.0.0 
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: "mongodb+srv://scastrod:Camaro110902@arqui.qecbh5s.mongodb.net/"  
